# Generated by Django 5.1.4 on 2024-12-28 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name': '在庫管理', 'verbose_name_plural': '在庫管理'},
        ),
        migrations.AlterUniqueTogether(
            name='management',
            unique_together={('customer_id', 'stock_id')},
        ),
        migrations.AlterField(
            model_name='management',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='顧客'),
        ),
        migrations.AlterField(
            model_name='management',
            name='pieces',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='management',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='disc',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='商品画像'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.IntegerField(verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=100, verbose_name='商品名'),
        ),
        migrations.RemoveField(
            model_name='management',
            name='name',
        ),
    ]
